project:
  type: website

website:
  title: "WGS_Bacteria"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example_1.qmd
        text: 'Example #1' 
      - href: setup.qmd
        text: 'Set Up' 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

