name: bacterial-genomics-tutorial-sw8
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools
  - bwa
  - sickle
  - fastqc
  - python=3
  - minimap2
  - ragtag
  - abricate
  - mlst
  - spades=3.15.2
  - mummer
  - mash
  - roary
  - mafft
  - prokka
  #- quast
  - perl-padwalker
  - perl-db-file
  - porechop
  - sra-tools
  - sickle-trim
  - trimmomatic
  - fastani
  - pip
  - pip:
      - numpy
      - matplotlib
      - matplotlib-venn
      - biopython
      - dREP
