name: bacterial-genomics-tutorial-sw2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools
  - bwa
  - sickle
  - fastqc
  - python=3
  - minimap2
  - ragtag
  - abricate
  - mlst
  - spades
  # # duplicate
  # - minimap2
  # - mummer
  # - mash
  # - roary
  # - mafft
  # - prokka
  # - quast
  # - perl-padwalker
  # - perl-db-file
  # - porechop
  # - sra-tools
  # - sickle-trim
  # - trimmomatic
  # - pip
  # - pip:
  #     - numpy
  #     - matplotlib
  #     - matplotlib-venn
  #     - biopython
  #     - dREP
